Code/Website/LifeManagement/Models/Sprint.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sprint()
        {
            this.Goals = new HashSet<Goal>();
            this.SprintActivities = new HashSet<SprintActivities>();
        }
    
        public int Id { get; set; }
        public string SprintGoal { get; set; }
        public System.DateTime DateFrom { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Goal> Goals { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SprintActivities> SprintActivities { get; set; }
    }
}

Code/Website/LifeManagement/Models/SprintViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LifeManagement.Models
{
    public class SprintViewModel
    {

  
        public string SprintGoal { get; set; }

        public string JoyGoal { get; set; }

        public string PassionGoal { get; set; }

        public string GiveBGoal { get; set; }

        public Activity ActJoy1 { get; set; }

        public Activity ActJoy2 { get; set; }

        public Activity ActJoy3 { get; set; }

        public Activity ActPassion1 { get; set; }

        public Activity ActPassion2 { get; set; }

        public Activity ActGiveB1 { get; set; }

        public Activity ActGiveB2 { get; set; }


    }
}

Code/Website/LifeManagement/Controllers/SprintsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls.WebParts;
using LifeManagement.Models;

namespace LifeManagement.Controllers
{
    public class SprintsController : Controller
    {
        private SeniorDBEntities db = new SeniorDBEntities();
        // GET: Sprints
        public ActionResult Index()
        {
            return View();
        }

        // GET: Sprints/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public PartialViewResult NewSprint()
        {
            return PartialView();
        }

        public PartialViewResult StartNewSprint()
        {
            return PartialView();
        }

        public PartialViewResult ScoreSummary(int id)
        {
            var sprint = db.Sprints.Find(id);
            if(sprint!=null)
            return PartialView(sprint);

            ViewBag.ErrorMsg = "Could not get summary";
            return PartialView("ErrorPartial");
        }

        public ActionResult ScoreSummaryCoaches(int id)
        {
            var sprint = db.Sprints.Find(id);
           
            if (sprint != null) {
                var user = db.Users.Find(sprint.UserId);

                if (user != null)
                {
                    ViewBag.NameUser = user.FirstName + " " + user.LastName;
                }
                return View(sprint);

            }

            ViewBag.ErrorMsg = "Could not get summary";
            return View("Error");
        }

        // GET: Sprints/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: Sprints/Create
        [HttpPost]
        public ActionResult Create(Sprint newSprint)
        {
            try
            {
                // TODO: Add insert logic here
                var user = (db.Users.Where(a => a.username.ToLower() == (User.Identity.Name).ToLower()).FirstOrDefault());
                var lastsprint = db.Sprints.Where(a => a.UserId == user.Id).OrderByDescending(a => a.DateFrom).FirstOrDefault();

                if (user != null)
                {
                    newSprint.UserId = user.Id;
                    db.Sprints.Add(newSprint);
                    db.SaveChanges();

                    var sprintActivities = lastsprint.SprintActivities;

                    foreach (SprintActivities sp in sprintActivities.ToList())
                    {
                        var newsprintA = new SprintActivities();
                        newsprintA = sp;
                        newsprintA.SprintId = newSprint.Id;
                        db.SprintActivities.Add(newsprintA);
                        db.SaveChanges();
                    }

                    var sprintGoals = lastsprint.Goals;
                    var goal1 = new Goal();
                    var goal2 = new Goal();
                    var goal3 = new Goal();

                    foreach (Goal g in sprintGoals.ToList())
                    {
                        var newGoal = new Goal();
                        newGoal = g;
                        newGoal.SprintId = newSprint.Id;
                        db.Goals.Add(newGoal);
                        db.SaveChanges();

                        switch (newGoal.CategoryId)
                        {
                            case 1: goal1 = newGoal; break;
                            case 2: goal2 = newGoal; break;
                            case 3: goal3 = newGoal; break;
                        }
                    }

                    ViewBag.goalJoy = goal1.Description;
                    ViewBag.goalPassion = goal2.Description;
                    ViewBag.goalGB = goal3.Description;

                    TempData["newSprint"] = newSprint;
                    TempData.Keep("newSprint");

                    return View("ConfigureNewSprint", newSprint);
                }
                else
                {
                    ViewBag.ErrorMsg = "There is no user logged in";
                    return PartialView("ErrorPartial");
                }

            }
            catch
            {
                ViewBag.ErrorMsg = "There was an unexpected error";
                return PartialView("ErrorPartial");
            }
        }

        public ActionResult ConfigureNewSprint()
        {
            var user = db.Users.Where(a => a.username.ToLower() == User.Identity.Name.ToLower()).FirstOrDefault();

            var lastsprint =
                db.Sprints.Where(a => a.UserId == user.Id).OrderByDescending(a => a.DateFrom).FirstOrDefault();

            var newSprint = new Sprint();
            newSprint.SprintGoal = lastsprint.SprintGoal;
            newSprint.DateFrom = DateTime.Now;
            newSprint.UserId = user.Id;
            db.Sprints.Add(newSprint);
            db.SaveChanges();

            var sprintActivities = lastsprint.SprintActivities;
            
            foreach(SprintActivities sp in sprintActivities.ToList())
            {
                var newsprintA = new SprintActivities();
                newsprintA = sp;
                newsprintA.SprintId = newSprint.Id;
                db.SprintActivities.Add(newsprintA);
                db.SaveChanges();
            }

            var sprintGoals = lastsprint.Goals;
            var goal1 = new Goal();
            var goal2 = new Goal();
            var goal3 = new Goal();

            foreach (Goal g in sprintGoals.ToList())
            {
                var newGoal = new Goal();
                newGoal = g;
                newGoal.SprintId = newSprint.Id;
                db.Goals.Add(newGoal);
                db.SaveChanges();

                switch (newGoal.CategoryId)
                {
                    case 1: goal1 = newGoal; break;
                    case 2: goal2 = newGoal; break;
                    case 3: goal3 = newGoal; break;
                }
            }

            ViewBag.goalJoy = goal1.Description;
            ViewBag.goalPassion = goal2.Description;
            ViewBag.goalGB = goal3.Description;

            TempData["newSprint"] = newSprint;
            TempData.Keep("newSprint");

            return View(newSprint);

        }

        [HttpPost]
        public ActionResult ConfigureNewSprint( QuestionarieViewModel quest)
        {
            if(TempData["newSprint"] != null)
            {
                var sprint = TempData["newSprint"] as Sprint;

                Sprint newSprint = db.Sprints.Find(sprint.Id);

                if (quest.vision != newSprint.SprintGoal && quest.vision != null)
                {
                    newSprint.SprintGoal = quest.vision;        //Im using vision as the SprintGoal to reuse the previos QuestionnaireViewModel
                    db.SaveChanges();
                }

                var sprintGoals = newSprint.Goals;
     
            string goalJoy = quest.goal_1;
            string goalPassion = quest.goal_2;
            string goalGB= quest.goal_3;

                foreach (Goal g in sprintGoals.ToList())
                {
                    Goal newGoal = db.Goals.Find(g.Id);
                    
                    if(newGoal.CategoryId == 1 && newGoal.Description != goalJoy && goalJoy != null)
                    { 
                    newGoal.Description = goalJoy;
                    db.SaveChanges();
                    }
                    else if (newGoal.CategoryId == 2 && newGoal.Description != goalPassion && goalPassion != null)
                    {
                        newGoal.Description = goalPassion;
                        db.SaveChanges();
                    }
                    else if (newGoal.CategoryId == 3 && newGoal.Description != goalGB && goalGB != null)
                    {
                        newGoal.Description = goalGB;
                        db.SaveChanges();
                    }
                }

                return RedirectToAction("Dashboard", "Users");
            }
            ViewBag.ErrorMsg = "There was an unexpected error while configuring your productivity week, try again later";
            return View("Error");
        }

            public ActionResult SetupSprint()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SetupSprint(SprintViewModel model)
        {
            if(model != null)
            return View();

            ViewBag.ErrorMsg = "An error ocurred";
            return View("Error");
        }

        // GET: Sprints/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Sprints/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Sprints/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Sprints/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Code/Website/LifeManagement/Views/Sprints/ConfigureNewSprint.cshtml
<script src="~/Scripts/CatTiles.js"></script>
<link href="~/Content/CatTiles.css" rel="stylesheet" />

@model LifeManagement.Models.Sprint

@{
    Layout = "~/Views/Shared/_layout_for_questionarie.cshtml";
}



@section AddToHead{
    <link rel="stylesheet" type="text/css" href="~/Content/bety_css/normalize.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/bety_css/demo.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/bety_css/component.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/bety_css/cs-select.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/bety_css/cs-skin-boxes.css" />
    <script src="~/Scripts/bety_scripts/modernizr.custom.js"></script>
}



<div class="modal-body" style="width: 1200px ; height: 680px; position: absolute; margin:0 auto!important ; padding: 0!important">

    <div class="container" style="background: url('/Imgs/bety_new_img/wave.jpg') no-repeat; background-size: 100% 100%;  padding: 0!important">
        <div class="fs-form-wrap" id="fs-form-wrap">
            <div class="fs-title">

                <h1 style="font-weight: bold"> Productivity week setup </h1>
                <br />
                <div style=" width: 1050px ; height: 50px; font-size: 14px ; position: absolute; left: 50px">
                    <h1 style=" color: black; font-weight: bold">Note: <br />   Click continue if you want to keep the settings of your last productivity week. </h1>
                </div>
            </div>


            <form id="myform" class="fs-form fs-form-full" autocomplete="off" action="@Url.Action("ConfigureNewSprint", "Sprints")" method="post">
                <ol class="fs-fields">
                    <li>
                        <label class="fs-field-label fs-anim-upper" for="vision" style="color: black ; font-weight: 800" data-info="Goals - are broad open ended statements to achieve your vision. They describe what you want to achieve through your efforts."> Enter a general goal that you want to achieve this period, or click 'Continue' to use the one from previous period.</label>
                        <textarea style="" class="fs-anim-lower" id="vision" name="vision" required>@Model.SprintGoal</textarea>
                    </li>
                    <li>
                        <label class="fs-field-label fs-anim-upper" for="goal_1" style="color: black ; font-weight: 800" data-info="Goals - are broad open ended statements to achieve your vision. They describe what you want to achieve through your efforts."> Enter a goal for this period that gives you joy, or click 'Continue' to use the one from previous period.</label>
                        <textarea class="fs-anim-lower" id="goal_1" name="goal_1" required>@ViewBag.goalJoy</textarea>
                    </li>

                    <li>
                        <label class="fs-field-label fs-anim-upper" for="goal_2" style="color: black ; font-weight: 800" data-info="Goals - are broad open ended statements to achieve your vision. They describe what you want to achieve through your efforts."> Enter a goal for this period that you are passionate about, or click 'Continue' to use the one from previous period.</label>
                        <textarea class="fs-anim-lower" id="goal_2" name="goal_2" required>@ViewBag.goalPassion</textarea>
                    </li>

                    <li>
                        <label class="fs-field-label fs-anim-upper" for="goal_3" style="color: black ; font-weight: 800" data-info="Goals - are broad open ended statements to achieve your vision. They describe what you want to achieve through your efforts."> Enter a goal for this period to give back to others, or click 'Continue' to use the one from previous period. </label>
                        <textarea class="fs-anim-lower" style=" font:14px " id="goal_3" name="goal_3" required>@ViewBag.goalGB</textarea>
                    </li>

                    <li>
                        <div class="cycle-tab fs-anim-lower fs-anim-upper" style="background-color: cadetblue">
                            <label class="fs-field-label fs-anim-upper" style=" font-weight: 800" data-info="Select upto 3 activities that give you joy">What gives you joy?</label>

                            <div class="fs-anim-lower fs-anim-upper activities-div" id="joytab">
                                @{Html.RenderAction("Joy", "SprintActivities", new { id = Model.Id });}
                            </div>
                        </div>


                    </li>
                    <li>
                        <div class="cycle-tab fs-anim-lower fs-anim-upper" style="background-color: #ffb3b3">
                            <label class="fs-field-label fs-anim-upper" style=" font-weight: 800" data-info="Select upto 2 activities that you are really passionate about">What are you passionate about?</label>

                            <div class="fs-anim-lower fs-anim-upper activities-div" id="passiontab">
                                @{Html.RenderAction("Passion", "SprintActivities", new { id = Model.Id });}
                            </div>
                        </div>


                    </li>
                    <li>
                        <div class="cycle-tab fs-anim-lower fs-anim-upper" style="background-color: #ffa366">

                            <label class="fs-field-label fs-anim-upper" for="vision" style=" font-weight: 800" data-info="Select upto 2 activities that give you a sense of fulfilment from giving back or helping others">How would you give back to society?</label>

                            <div class="fs-anim-lower fs-anim-upper activities-div" id="gbtab">
                                @{Html.RenderAction("GivingBack", "SprintActivities", new { id = Model.Id });}
                            </div>
                        </div>
                    </li>


                </ol><!-- /fs-fields -->

                <button class="fs-submit" type="submit">Send answers</button>
            </form><!-- /fs-form -->
        </div><!-- /fs-form-wrap -->
        <!-- Related demos -->
    </div> <!-- /container -->
</div>

<script src="~/Scripts/bety_scripts/classie.js"></script>
<!--     <script src="~/Scripts/bety_scripts/selectFx.js"></script>   -->
<script src="~/Scripts/bety_scripts/fullscreenForm.js"></script>
<script>
                (function () {
                    var formWrap = document.getElementById('fs-form-wrap');

                    [].slice.call(document.querySelectorAll('select.cs-select')).forEach(function (el) {
                        new SelectFx(el, {
                            stickyPlaceholder: false,
                            onChange: function (val) {
                                document.querySelector('span.cs-placeholder').style.backgroundColor = val;
                            }
                      });
                    });

                    new FForm(formWrap, {
                        onReview: function () {
                            classie.add(document.body, 'overview'); // for demo purposes only
                        }
                    });
                })();
</script>

<script>


    function submitAll(cat) {

       var activities=[];debugger;
        $('.cat-tiles-chk:checkbox:checked').each(function() {
            var id = $(this).attr('id');
            var s = $('#spec-' + id + ' :input').val();
            s = (s == null || s=='' ? "Not specified" : s);
            var act = {
                activityId: parseInt(id),
                sprintId: parseInt(@Model.Id),
                spec:s
            }

            activities.push(act);

        });

        updateSprintActivity(activities,cat);


    }
   function updateSprintActivity(activities,cat) {
       debugger;

       var tabid="#joytab";
       if (cat == 'passion')
           tabid = "#passiontab";
       if (cat == 'gb')
           tabid = "#gbtab";

        $.ajax({
            url: '@Url.Action("UpdateSprint","SprintActivities")',
            type: 'POST',

            data:{ 'activities': activities,cat:cat } ,
            success:function(res) {

               $(tabid).html(res);
            },
            error:function(msg) {
                $(tabid).html('<h4>Could not get data from server </h4>');
            }
        })

    }

    function renderCardBlock(url, tabid) {
        debugger;
        var sprintid = @Model.Id;
        $('.nav-link').css('background-color', 'transparent');
        $(tabid).css('background-color', '#eeeeee');

        var data = { id: sprintid };

        $.ajax({
            url: url,
            data: data,
            type: 'GET',
            success:function(res) {
                $('#cardblock').html(res);

            },
            error: function (msg) {
                $('#cardblock').html('<h4>Could not get data from server </h4>');
            }
        })
    }


    $(document).on({
        ajaxStart: function () { $("#cardblock").addClass("loading"); },
        ajaxStop: function () { $("#cardblock").removeClass("loading");  }
    });



</script>

Code/Website/LifeManagement/Views/Sprints/Create.cshtml
@model LifeManagement.Models.Sprint

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>New productivity chart</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SprintGoal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SprintGoal, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateFrom, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                @Html.ValidationMessageFor(model => model.DateFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

Code/Website/LifeManagement/Views/Sprints/NewSprint.cshtml
<div class="clearfix">
   
        <h2 class="col-md-12 text-center"> It looks like your productivy week has ended!</h2>

        <h4 class="col-md-12 text-center"> Click continue to configure your next period</h4>

       
        <div class="form-group">
            <div class="col-md-offset-8 col-md-4">
                <button class="btn btn-success form-control" onclick="redirect()">
                    Continue
                </button>
            </div>
        </div>

   
    </div>


    <script>
    function redirect()
    {
        window.location.href = '@Url.Action("ConfigureNewSprint", "Sprints")'; 
    }
    </script>

Code/Website/LifeManagement/Views/Sprints/ScoreSummary.cshtml
@model LifeManagement.Models.Sprint

<div class="clearfix">
    <div class="col-md-12" id="tableForPic">
        <table class="table text-center">
            <tr>
                <th class="text-center" colspan="2">
                    @Model.SprintGoal
                </th>
               
            </tr>
            <tr>
                <th class="text-center" colspan="2">
                    Joy
                </th>
            </tr>
            <tr>
                <td>@Model.Goals.Where(a => a.Category.Name == "Joy").FirstOrDefault().Description</td>
                <td class="text-right">
                   
                    <div id="gaugeCat-Joy" class="gauge gauge-big gauge-green">

                        <div class="gauge-arrow" data-percentage="40"
                             style="transform: rotate(0deg);"></div>


                    </div>
                </td>
            </tr>
            <tr>
                <th class="text-center" colspan="2">
                    Passion
                </th>
            </tr>
            <tr>
                <td>@Model.Goals.Where(a => a.Category.Name == "Passion").FirstOrDefault().Description</td>
                <td class="text-right">
                   
                        <div id="gaugeCat-Passion" class="gauge gauge-big gauge-green">

                            <div class="gauge-arrow" data-percentage="40"
                                 style="transform: rotate(0deg);"></div>


                        </div>

                </td>
            </tr>
            <tr>
                <th class="text-center" colspan="2">
                    Giving Back
                </th>
            </tr>
            <tr>
                <td>@Model.Goals.Where(a => a.Category.Name == "Giving Back").FirstOrDefault().Description</td>
                <td class="text-right">
                   <div id="gaugeCat-GivingBack" class="gauge gauge-big gauge-green">

                            <div class="gauge-arrow" data-percentage="40"
                                 style="transform: rotate(0deg);"></div>


                        </div>
                </td>
            </tr>
           
            <tr>
                <th class="text-center" colspan="2">
                    Cycle
                </th>
            </tr>
            <tr>
                <td class="text-center" colspan="2">
                   
                    <div id="gaugeCycle" class="gauge gauge-big gauge-green">

                        <div class="gauge-arrow" data-percentage="40"
                             style="transform: rotate(0deg);"></div>


                    </div>
                  
                </td>
            </tr>
            <tr>
                <td colspan="2" class="text-right">
                    <button onclick="shareSummary()" class="btn btn-primary "> <span class="glyphicon glyphicon-share"></span> Share</button>
                </td>
            </tr>
        </table>
       

    </div>
  
   
    
</div>

<script>
    function shareSummary() {

               $.ajax({
                    url: '@Url.Action("ShareProgress", "Coaches")',
                    type: 'POST',
                    data: {id: @Model.Id},
                   success: function (res) {
                       renderDiv('@Url.Action("SeeCoachesUsers", "Coaches")', null);
                       
                    },
                    error: function () {
                        alert("Error sharing, try again later.");
                    }
                });
    }
</script>
 

Code/Website/LifeManagement/Views/Sprints/StartNewSprint.cshtml
<div class="clearfix">
   
    <h2 class="col-md-12 text-center"> Start a new productivity period! </h2>
    <hr />
    <p> <strong>If this productivity chart does not match your current goals, you can always start a new one.</strong></p>
    <p class="text-danger"> *Please Note, that by clicking continue you will lose access to this productivity chart</p>  
    <br />
    <h4 class="col-md-12 text-left"> <strong>Click continue to configure your next period</strong></h4>
    
       
        <div class="form-group">
            <div class="col-md-offset-4 col-md-4">
                <button class="btn btn-success form-control" onclick="redirect()">
                    Continue
                </button>
                </div>
            <div class="col-md-4">
                <button class="btn btn-primary form-control" data-dismiss="modal">Cancel</button>
            </div>
        </div>

   
    </div>


    <script>
    function redirect()
    {
        window.location.href = '@Url.Action("ConfigureNewSprint", "Sprints")'; 
    }
    </script>