Code/Website/LifeManagement/Models/Activity.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.CreatorId = -1;
            this.Approved = false;
            this.SprintActivities = new HashSet<SprintActivities>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public byte[] Img { get; set; }
        public string ImgMime { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SprintActivities> SprintActivities { get; set; }
        public virtual Category Category { get; set; }
    }
}

Code/Website/LifeManagement/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LifeManagement.Models;
using System.Drawing;
using System.Drawing.Imaging;

namespace LifeManagement.Controllers
{
    public class ActivitiesController : Controller
    {
        private Common common = new Common();
        private SeniorDBEntities db = new SeniorDBEntities();
        /*******************approve user activities******************/
        public PartialViewResult Revise()
        {
            return PartialView();
        }
        [Authorize(Roles = "Admin")]
        public PartialViewResult PendingList()
        {
            var pending = db.Activities.Where(a => a.ApprovedBy == null);
            if (pending.Any())
                return PartialView("PendingList", pending.ToList());

            ViewBag.ErrorMsg = "No pending reviews";
            return PartialView("ErrorPartial");

        }

        public PartialViewResult Details(int id)
        {
            var review = db.Activities.Find(id);
            if (review == null)
            {
                ViewBag.ErrorMsg = "Invalid review";
                return PartialView("ErrorPartial");
            }
            return PartialView(review);
        }

        public PartialViewResult CompleteReview(int id, bool isApproved)
        {
            var admin = db.Users.Where(a => a.username.ToLower() == User.Identity.Name.ToLower() && a.Role.Name == "Admin").FirstOrDefault();
            if (admin == null)
            {
                ViewBag.ErrorMsg = "Cannot approve or reject. Not an admin";
                return PartialView("ErrorPartial");
            }
            var act = db.Activities.Find(id);
            if (act == null)
            {
                ViewBag.ErrorMsg = "Invalid review";
                return PartialView("ErrorPartial");
            }
            db.Entry(act).State = EntityState.Modified;

            act.Approved = isApproved;
            act.DateApproved = DateTime.Now;
            act.ApprovedBy = admin.Id;
            db.SaveChanges();

          
            return PendingList();


        }
        /***************************customs************************/


        public PartialViewResult Joy()
        {
            var user = db.Users.Where(a => a.username.ToLower() == User.Identity.Name.ToLower()).FirstOrDefault();
            if (user == null)
            {
                ViewBag.ErrorMsg = "Invalid user";
                return PartialView("ErrorPartial");
            }
            try
            {
                var activities = db.Activities.Where(a => a.Category.Name == "Joy" && (a.Approved==true || a.CreatorId==user.Id)).ToList();
                return PartialView("Joy",activities);
            }
            catch (Exception e)
            {

                return PartialView(null);
            }

        }
        public PartialViewResult Passion()
        {
            var user = db.Users.Where(a => a.username.ToLower() == User.Identity.Name.ToLower()).FirstOrDefault();
            if (user == null)
            {
                ViewBag.ErrorMsg = "Invalid user";
                return PartialView("ErrorPartial");
            }
            try
            {
                var activities = db.Activities.Where(a => a.Category.Name == "Passion" && (a.Approved == true || a.CreatorId == user.Id)).ToList();
                return PartialView("Passion",activities);
            }
            catch (Exception e)
            {

                return PartialView(null);
            }

        }
        public PartialViewResult GivingBack()
        {
            var user = db.Users.Where(a => a.username.ToLower() == User.Identity.Name.ToLower()).FirstOrDefault();
            if (user == null)
            {
                ViewBag.ErrorMsg = "Invalid user";
                return PartialView("ErrorPartial");
            }
            try
            {
                var activities = db.Activities.Where(a => a.Category.Name == "Giving Back" && (a.Approved == true || a.CreatorId == user.Id)).ToList();
                return PartialView("GivingBack",activities);
            }
            catch (Exception e)
            {

                return PartialView(null);
            }

        }

        public PartialViewResult CatDisplay(string cat)
        {
            var activities = db.Activities.Where(a => a.Category.Name.ToLower() == cat.ToLower());
            if (activities.Any())
                return PartialView(activities.ToList());

            ViewBag.ErrorMsg = "Could not find any activity with the given category";
            return PartialView("ErrorPartial");
        }
        /****************Testing Bea******************/
        public PartialViewResult CreateActivity()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            return PartialView();
        }
        [HttpPost]
        public ActionResult CreateActivity(string Name, int CategoryId)
        {
   
            var file = Request.Files[0];

            Activity activity = new Activity();
            activity.Name = Name;
            activity.CategoryId = CategoryId;

            if (common.saveImageBytes(activity, file))
                {

                    activity.Img = common.ResizeImageFile(activity.Img, 200);

                    db.Activities.Add(activity);
                    db.SaveChanges();
                    ViewBag.Msg = "Activity Successfully saved";
                    return RedirectToAction("Dashboard", "Users");
            }

            ViewBag.ErrorMsg = " An unexpected error has occurred, try again later";
            return View("Error");

        }



        /*********************system generated**********************/
        // GET: Activities
      
    
        // GET: Activities/Create
        [HttpPost]
        public PartialViewResult Create(string name, string category)
        {
            var user = db.Users.Where(a => a.username.ToLower() == User.Identity.Name.ToLower()).FirstOrDefault();
            if (user == null)
            {
                ViewBag.ErrorMsg = "Invalid user";
                return PartialView("ErrorPartial");
            }
            var cat = db.Categories.Where(a => a.Name.ToLower() == category.ToLower()).FirstOrDefault();
            if (cat == null)
            {
                ViewBag.ErrorMsg = "Invalid category";
                return PartialView("ErrorPartial");
            }

            var file = Request.Files[0];

            Activity activity = new Activity();
            activity.Name = name;
            activity.CategoryId = cat.Id;
            activity.Approved = null;
            activity.CreatorId = user.Id;
        

            if (common.saveImageBytes(activity, file))
            {

                activity.Img = common.ResizeImageFile(activity.Img, 200);

                db.Activities.Add(activity);
                db.SaveChanges();
                if (cat.Name == "Joy")
                    return Joy();
                if (cat.Name == "Passion")
                    return Passion();

                return GivingBack();

            }

            ViewBag.ErrorMsg = " An unexpected error has occurred, try again later";
            return PartialView("ErrorPartial");
        }

      

        public PartialViewResult EditActivity()
        {

            return PartialView();
        }
        public PartialViewResult EditSelectedActivity(int id)
        {
            var act = db.Activities.Find(id);
            if (act == null)
            {
                ViewBag.ErrorMsg = "Could not find activity";
                return PartialView("ErrorPartial");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", act.CategoryId);
            return PartialView(act);
        }
        [HttpPost]
        public bool SaveEditActivity(int id,string name,int cat)
        {
            try
            {
                var act = db.Activities.Find(id);
                if (act == null)
                {
                    return false;
                }
                act.Name = name;
                act.CategoryId = cat;
                var file = Request.Files[0];
                if (common.saveImageBytes(act, file))
                {

                    act.Img = common.ResizeImageFile(act.Img, 200);


                    db.SaveChanges();
                    return true;
                }
                return false;
            }
            catch (Exception e)
            {
                return false;
            }
        }
        // GET: Activities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", activity.CategoryId);
            return View(activity);
        }

        // POST: Activities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,CategoryId,Img,ImgMime")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", activity.CategoryId);
            return View(activity);
        }

Code/Website/LifeManagement/Views/Activities/CreateActivity.cshtml
@model LifeManagement.Models.Activity



<div class="modal-body" style="width: 500px ; position: center ; margin:0 auto">
       <div id="responseOk">

       </div> 

        <div class="form-horizontal" id="completeForm">
            <h2 class="text-center"> Create Activity</h2>

            <br />

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <h5 id="EmptyName" class="col-md-offset-4 text-danger"></h5>
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <div class="form-group">
                <div class="control-label col-md-4">
                    <label> Choose a category</label>
                </div>
                <div class="col-md-8">
                    @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                </div>
            </div>


            <br />

            <div class="form-group">
                <h5 id="noFile" class="col-md-offset-4 text-danger"></h5>
                <div class="control-label col-md-4"> 
                    <label style="text-align:left">Upload Image:</label>
                </div>
                <div class="col-md-8">
                    <input type="file" name="file" id="file" style="width: 100%;" />
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-4">
                    <div class="col-md-4">
                        <button onclick="validate()" class="btn btn-success form-control">Create</button>
                       
                    </div>
                    <div class="col-md-4">
                        <button class="btn btn-danger" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </div>

        </div>
    </div>


<script src="~/Scripts/lmpopup.js"></script>

<script>
    function validate() {

        if ($("#Name").val() == "") {
            $("#EmptyName").html("Please enter a name for the activity");
            return;
        }

        if ($("#file").val() == "") {
            $("#noFile").html("Upload a file to continue");
            return;
        }

        if (($("#file")[0].files[0].size) >= 2097152)       //2MB
        {
            $("#noFile").html("Image too big, please upload a pic of 2MB or less");
            return;
        }

        var formdata = new FormData();

        var fileInput = $('#file');
        $.each($(fileInput).get(0).files, function (index, value) {
            formdata.append(value.name, value);
        });

        var Name = $("#Name").val();
        var CategoryId = parseInt($("#CategoryId").val());

        formdata.append("Name", Name);
        formdata.append("CategoryId", CategoryId);

 

  $.ajax({
            url: '@Url.Action("CreateActivity", "Activities")',
            type: 'POST',
            data: formdata,
            contentType: false,
            cache: false,
            processData: false,
            success: function (res) {
                $("#responseOk").html("<h2> The Activity was created successfully </h2> <button class=\"btn btn-success\" data-dismiss=\"modal\">Done</button>");
                $("#completeForm").html('');
            },
            error: function (msg) {
                $("#responseOk").html("<h2> Some unexpected error happened </h2> <button class=\"btn btn-danger\" data-dismiss=\"modal\">Close</button>");
                $("#completeForm").html('');
            }
        });
    }
</script>


   

Code/Website/LifeManagement/Views/Activities/DeleteSelectedActivity.cshtml
@model LifeManagement.Models.Activity

@{
    var common = new LifeManagement.Models.Common();
}

<div id="finalresp">
    
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Category.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Category.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Img)
            </dt>

            <dd>
                <div class="coach-avatar-container">
                    <img class=" coach-avatar-img " src="@common.SignatureImageStr64(Model.Img, Model.ImgMime)">
                </div>
            </dd>
        </dl>

        <br />
        <br />
        <div class="form-group">
            <div class="col-md-offset-4">
                <div class="col-md-4">
                    <button onclick="validate()" class="btn btn-success form-control">Delete</button>

                </div>
                <div class="col-md-4">
                    <button class="btn btn-danger" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
        <br />
        <br />
    </div>





<script>
    function validate() {
        $.ajax({
            url: '@Url.Action("DeleteConfirmed", "Activities")',
            type: 'POST',
            data: {id: @Model.Id},
            success: function (res) {
                $("#finalresp").html("<h2> The activity was deleted successfully </h2> <button class=\"btn btn-success\" data-dismiss=\"modal\">Done</button>");
             },
            error: function (msg) {
                alert("Error");
            }
        });
    }
</script>

Code/Website/LifeManagement/Views/Activities/Details.cshtml
@model LifeManagement.Models.Activity
@{
    LifeManagement.Models.Common common = new LifeManagement.Models.Common();
}
<link href="~/Content/Reviews.css" rel="stylesheet" />
<div class="clearfix">


    <div class="col-md-12">
        <div id="approveerrors" class="text-danger"></div>
    </div>
    <div class="col-md-12 text-center">
        <div class="cat-tiles col-sm-4 col-md-4 col-md-offset-4" style="margin-left: 33.33%!important;margin-bottom: 5px">
            <label id="lbl" for="@Model.Id">
                <div class="cat-tiles-body">

                    <img class="cat-tiles-img" src="@common.SignatureImageStr64(Model.Img, Model.ImgMime)" />
                </div>
            </label>
            <div class="cat-tiles-footer">
                <input class="cat-tiles-chk chk-cat" type="checkbox" id="@Model.Id" />
                <label class="cat-tiles-lbl">@Model.Name</label>
            </div>


        </div>
    </div>
        <div class="col-md-12 text-center">
            <button class="btn btn-sm btn-success" onclick="revise(true)">Approve</button>
            <button class="btn btn-sm btn-danger" onclick="revise(false)">Reject</button>
        </div>
    </div>


               
<script>
    function revise(isApproved) {
        var data= {
            id:@Model.Id,
            isApproved:isApproved
        }
        $.ajax({
            url: '@Url.Action("CompleteReview","Activities")',
            type: 'POST',
            data: data,
            success: function(msg) {
                $("#pending-list").html(msg);
                $("#basicModal").modal('hide');
            },
            error: function(res) {
                $("#approveerrors").html("Could not complete review")
            }
        });
    }
</script>
<style>
    .review-div {
        max-height: 1000px !important;
    }
</style>

Code/Website/LifeManagement/Views/Activities/EditActivity.cshtml
<script src="~/Scripts/lmpopup.js"></script>
<link href="~/Content/CatTiles.css" rel="stylesheet" />
<script src="~/Scripts/cooltabs.js"></script>
<link href="~/Content/cooltabs.css" rel="stylesheet" />

@{
    var common = new LifeManagement.Models.Common();
}


<div class="clearfix" id="torender">


    <h3 class="col-md-12"> Click the desired Category and select the Activity you want to edit</h3>


    <div class="col-md-12  bhoechie-tab-container">
        <div class="col-md-2  bhoechie-tab-menu">
            <div class="list-group">
                <a href="#" class="list-group-item active text-center">
                    <h4 class="glyphicon glyphicon-music"></h4><br />Joy
                </a>
                <a href="#" class="list-group-item text-center">
                    <h4 class="glyphicon glyphicon-heart"></h4><br />Passion
                </a>
                <a href="#" class="list-group-item text-center">
                    <h4 class="glyphicon glyphicon-backward"></h4><br />Giving Back
                </a>


            </div>
        </div>
        <div class="col-md-10 bhoechie-tab">

            <div class="bhoechie-tab-content active">

                <center>
                    @{Html.RenderAction("CatDisplay","Activities",new {cat="Joy"});}
                </center>

            </div>
            <div class="bhoechie-tab-content">

                <center>
                    @{Html.RenderAction("CatDisplay", "Activities", new { cat = "Passion" });}
                </center>

            </div>
            <div class="bhoechie-tab-content">

                <center>
                    @{Html.RenderAction("CatDisplay", "Activities", new { cat = "Giving Back" });}
                </center>

            </div>


        </div>
    </div>
</div>


<script>
  

    $('.chk-cat').on('change', function (evt) {
        var id = this.id;
        $.ajax({
            url: '@Url.Action("EditSelectedActivity","Activities")',
            type:'GET',
            data:{id:id},
            success:function(res) {
                $("#torender").html(res);
            },
            error:function(msg) {
                alert("error");
            }
        })

    });

 

</script>
 

Code/Website/LifeManagement/Views/Activities/EditSelectedActivity.cshtml
@model LifeManagement.Models.Activity



<div id="finalresp">

    <div class="form-horizontal">
        <h2 class="text-center"> Edit Activity</h2>
        @Html.HiddenFor(model=>model.Id)
      
        <div class="form-group">
            <h5 id="EmptyName" class="col-md-offset-4 text-danger"></h5>
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
          
            </div>
        </div>

     <div class="form-group">
            <div class="control-label col-md-4">
                <label> Choose a category</label>
            </div>
            <div class="col-md-8">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
          
            </div>
        </div>

        <div class="form-group">
            <h5 id="noFile" class="col-md-offset-4 text-danger"></h5>
            <div class="control-label col-md-4">
                <label style="text-align:left">Upload Image:</label>
            </div>
            <div class="col-md-8">
                <input type="file" name="file" id="file" style="width: 100%;" />
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-4">
                <div class="col-md-4">
                    <button onclick="validate()" class="btn btn-success form-control">Save</button>

                </div>
                <div class="col-md-4">
                    <button class="btn btn-danger" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>

    </div>
</div>




<script>
    function validate() {

        if ($("#Name").val() == "") {
            $("#EmptyName").html("Please enter a name for the activity");
            return;
        }

        if ($("#file").val() == "") {
            $("#noFile").html("Upload a file to continue");
            return;
        }

        if (($('#file')[0].files[0].size) >= 2097152)       //30KB
        {
            $("#noFile").html("Image too big, please upload a pic of 2 mb or less");
            return;
        }
        
        var formdata = new FormData();
       
        var fileInput = $('#file');
        $.each($(fileInput).get(0).files, function (index, value) {
            formdata.append(value.name, value);
        });
        var id = parseInt($("#Id").val());
        var catid = parseInt($("#CategoryId").val());
        var name = $("#Name").val();
      
        formdata.append("id", id);
        formdata.append("name", name);
        formdata.append("cat",catid);
    

        $.ajax({
            url: '@Url.Action("SaveEditActivity", "Activities")',
            type: 'POST',
            data:formdata,
            contentType:false,
            cache: false,
            processData:false,
          success: function (res) {
              $("#finalresp").html("<h2> The activity edited successfully </h2> <button class=\"btn btn-success\" data-dismiss=\"modal\">Done</button>");
          },
            error: function (msg) {
                alert("Error");
            }
        });
    }
</script>

Code/Website/LifeManagement/Views/Activities/GivingBack.cshtml
<div id="actdiv">
    @model List<LifeManagement.Models.Activity>
    @{
        var common = new LifeManagement.Models.Common();
    }






    <div id="gberror" class="text-danger" style="display: none"><h4>Need to select two activities</h4></div>


    <div class="clearfix">
        <h4 class="col-md-12 text-center" style="color:white">Select two activities in which you would like to give back</h4>
        <div class="col-md-12 text-center">
            @if (Model != null)
            {
                foreach (var a in Model)
                {

                    <div class="cat-tiles col-sm-4 col-md-3">
                        <label id="lbl" for="@a.Id">
                            <div class="cat-tiles-body">

                                <img class="cat-tiles-img" src="@common.SignatureImageStr64(a.Img, a.ImgMime)" />
                            </div>
                        </label>
                        <div class="cat-tiles-specifics" id="spec-@a.Id">
                            <textarea placeholder="Specify activities" class="cat-tiles-spec-text" rows="1"></textarea>
                        </div>
                        <div class="cat-tiles-footer">
                            <input class="cat-tiles-chk chk-gb" type="checkbox" id="@a.Id" />
                            <label class="cat-tiles-lbl">@a.Name</label>
                        </div>


                    </div>

                }
            }

        </div>

        <div class="col-md-12 text-right"><button class="btn btn-success" onclick="saveGb()">Save</button></div>
        <div class="col-md-12">
            <button class="btn btn-sm btn-info" onclick="showform()">Cant find activity?</button>
        </div>
        <div class="form-horizontal col-md-4 col-md-offset-4 form-hide" id="addform">
            <div id="uploaderrors" class="text-danger">

            </div>
            <div class="form-group">
                <div class="col-md-12">
                    <input type="text" id="name" class="form-control" />
                </div>

            </div>

            <div class="form-group">
                <label class="control-label col-md-4">Upload Image:</label>
                <div class="col-md-8">
                    <input type="file" name="file" id="file" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-4 col-md-4">
                    <button onclick="validate()" class="btn btn-success form-control">Create</button>
                </div>
            </div>



        </div>
    </div>

    <script>
        var gblimit = 2;


        $('.chk-gb').on('change', function (evt) {
            var isInsert = this.checked;

            if (isInsert) {
                var l = $('.chk-gb:checkbox:checked').length;

                if (l >= gblimit + 1) {
                    this.checked = false;
                    return;
                } else {

                    $("#spec-" + this.id + " .cat-tiles-spec-text").css('background-color', 'aliceblue');
                }
            } else {

                $("#spec-" + this.id + " .cat-tiles-spec-text").css('background', 'white');
            }




        });
        function saveGb() {

            var l = $('.chk-gb:checkbox:checked').length;
            if (l != gblimit) {
                $("#gberror").show(200);
                return;
            } else {
                submitAll('gb');

                $("#basicModal").modal("hide");
            }

        }
    </script>
    <script>
        function showform() {
            $("#addform").toggle();
        }
        function validate() {

            if ($("#name").val() == "") {
                $("#uploaderrors").html("Please enter a name for the activity");
                return;
            }

            if ($("#file").val() == "") {
                $("#uploaderrors").html("Upload a file to continue");
                return;
            }

            if (($("#file")[0].files[0].size) >= 2097152)       //2MB
            {
                $("#uploaderrors").html("Image too big, please upload a pic of 2MB or less");
                return;
            }

            var formdata = new FormData();

            var fileInput = $('#file');
            $.each($(fileInput).get(0).files, function (index, value) {
                formdata.append(value.name, value);
            });
            debugger;
            var name = $("#name").val();


            formdata.append("name", name);
            formdata.append("category", "Giving Back");



            $.ajax({
                url: '@Url.Action("Create", "Activities")',
                type: 'POST',
                data: formdata,
                contentType: false,
                cache: false,
                processData: false,
                success: function (res) {
                    $("#actdiv").html(res);
                    showform();
                },
                error: function (msg) {
                    $("#uploaderrors").html("Some unexpected error happened");

                }
            });
        }



    </script>
</div>

Code/Website/LifeManagement/Views/Activities/PendingList.cshtml
@model List<LifeManagement.Models.Activity>
    @{
        LifeManagement.Models.Common common = new LifeManagement.Models.Common();
    }
<link href="~/Content/coaches.css" rel="stylesheet" />
<link href="~/Content/Reviews.css" rel="stylesheet" />
<link href="~/Content/CatTiles.css" rel="stylesheet" />

@foreach (var m in Model)
{
    <div class="review-div lmmodal" modal-width="600px" url="@Url.Action("Details","Activities",new {id=m.Id})">
        <div  style="float:left ">
            <img class="user-image" src="@common.SignatureImageStr64(m.Img,m.ImgMime)"/>

        </div>
        <div>
            @(@m.Category.Name+": "+ m.Name)
        </div>
    </div>
}
<script>
    $(document).ready(function() {
        setpopups();
    })
</script>

Code/Website/LifeManagement/Views/Activities/Revise.cshtml
<h4>Reviews Pending Approval </h4>
<div id="pending-list">
    @{Html.RenderAction("PendingList");}
</div>