Code/Website/LifeManagement/Models/Coach.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coach()
        {
            this.CoachReviews = new HashSet<CoachReview>();
            this.Forums = new HashSet<Forum>();
        }
    
        public int Id { get; set; }
        public int ReviewScore { get; set; }
        public string Biography { get; set; }
        public string Skills { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte[] Avatar { get; set; }
        public string AvatarMime { get; set; }
        public int RoleId { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoachReview> CoachReviews { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Forum> Forums { get; set; }
    }
}

Code/Website/LifeManagement/Models/CoachReview.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachReview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoachReview()
        {
            this.Approved = false;
        }
    
        public int Id { get; set; }
        public int CoachId { get; set; }
        public int UserId { get; set; }
        public string Review { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual Coach Coach { get; set; }
        public virtual User User { get; set; }
    }
}

Code/Website/LifeManagement/Models/CoachViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LifeManagement.Models
{
    public class CoachViewModel
    {

        [Required]
        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [Required]
        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [Required]
        [DisplayName("Biography")]
        public string Biography { get; set; }

        [Required]
        [DisplayName("Skills")]
        public string Skills { get; set; }

        [Required]
        [DisplayName("Username")]
        public string Username { get; set; }

        [Required]
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }


        [Required]
        [DisplayName("Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
    }
}

Code/Website/LifeManagement/Controllers/CoachesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LifeManagement.Models;
using System.Web.Security;

namespace LifeManagement.Controllers
{
    public class CoachesController : Controller
    {
        private SeniorDBEntities db = new SeniorDBEntities();
        private Common common = new Common();
        /**************working with coaches fernando******************/
        public JsonResult GetCoaches()
        {
            var coaches = db.Coaches;
            List<CoachListVM> result = new List<CoachListVM>();
            foreach (var a in coaches)
            {
                var newcoach = new CoachListVM()
                {
                    CoachId = a.Id,
                    AvatarStr64 = common.SignatureImageStr64(a.Avatar, a.AvatarMime),
                    FirstName = a.FirstName,
                    LastName = a.LastName,
                    Skills = a.Skills,
                    ReviewScore = a.ReviewScore
                };
                result.Add(newcoach);
            }
           
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult CoachesListAngular()
        {
            return PartialView();
        }
        public PartialViewResult CoachesChatList()
        {
            var coaches = db.Coaches.ToList();
            return PartialView(coaches);
        }
        public PartialViewResult CoachesList()
        {
            var coaches = db.Coaches.ToList();
            return PartialView(coaches);
        }
        public ActionResult SeeCoaches()
        {
            return View();
        }
        /*********************coach reviews***********************************/

        public ActionResult SeeReviews(int id)
        {
            return View(id);
        }

        public PartialViewResult CoachReviews(int id)
        {
            var coach = db.Coaches.Find(id);
            if (coach == null)
            {
                ViewBag.ErrorMsg = "Invalid coach";
                return  PartialView("ErrorPartial");
            }
            return PartialView(coach);
        }
        public PartialViewResult ReviewsList(int id)
        {
            var reviews = db.CoachReviews.Where(a=>a.CoachId==id && a.Approved==true);
            if (!reviews.Any())
            {
                ViewBag.NoReviews = "There are no reviews yet";

            }
            return PartialView(reviews.ToList());
        }
     
        public PartialViewResult WriteReview(int id)
        {
            return PartialView(id);
        }
   
        [HttpPost]
        public string SaveReview(int coachid, string review, int score)
        {
            if (String.IsNullOrEmpty(review))
            {
                Response.StatusCode = 500;
                return "Review cannot be empty";
            }

            var user = db.Users.Where(a => a.username.ToLower() == User.Identity.Name.ToLower()).FirstOrDefault();
            if (user == null)
            {
                Response.StatusCode = 500;
                return "Need to be a user";
            }
              
           
            var coach = db.Coaches.Find(coachid);
            if (coach == null)
            {
                Response.StatusCode = 500;
                return "Invalid coach";
            }
                
            
            coach.CoachReviews.Add(new CoachReview()
            {
                Review = review,
                Score = score,
                UserId = user.Id
                
            });
            db.SaveChanges();
            return "Review saved successfully";


        }
        /*********************************************************************/
        // GET: Coaches
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.Coaches.ToList());
        }

        // GET: Coaches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Coach coach = db.Coaches.Find(id);
            if (coach == null)
            {
                return HttpNotFound();
            }
            return View(coach);
        }

        // This is the page Users see
        public PartialViewResult CoachDetailsPage(int? id)
        {
            if (id == null)
            {
                return PartialView("ErrorPartial");
            }
            Coach coach = db.Coaches.Find(id);
            if (coach == null)
            {
                return PartialView("ErrorPartial");
            }
            return PartialView(coach);
        }

        // GET: Coaches/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Coaches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CoachViewModel coach)
        {
            if (ModelState.IsValid)
            {
                var role = db.Roles.Where(a => a.Name == Constants.ROLES.COACH).FirstOrDefault();

                if (db.Coaches.Where(a => a.Email.ToLower() == coach.Email.ToLower()).Count() > 0)
                {
                    ViewBag.DuplicateEmail = "This email address is already registered in the system.";
                    return View(coach);
                }

                if (db.Coaches.Where(a => a.Username.ToLower() == coach.Username.ToLower()).Count() > 0)
                {
                    ViewBag.DuplicateUserName = "That username is already taken, try another one";
                    return View(coach);
                }

                if (role != null)
                {

                    var coachOb = new Coach();
                    coachOb.FirstName = coach.FirstName;
                    coachOb.LastName = coach.LastName;
                    coachOb.ReviewScore = 5;    //5 by default
                    coachOb.Biography = coach.Biography;
                    coachOb.Skills = coach.Skills;
                    coachOb.Username = coach.Username;
                    coachOb.Password = Security.HashSHA1(coach.Password);
                    coachOb.RoleId = role.Id;
                    coachOb.Email = coach.Email;

                    db.Coaches.Add(coachOb);
                    db.SaveChanges();

                    return RedirectToAction("DashBoard", "Users");
                }
                else
                {
                    ViewBag.ErrorMsg = "Authentication error!";
                    View("Error");
                }
            }

            return View();
        }

        // GET: Coaches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Coach coach = db.Coaches.Find(id);
            if (coach == null)
            {
                return HttpNotFound();
            }

            return View(coach);
        }

        // POST: Coaches/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Coach coachData)
        {
            if (coachData.FirstName == null || coachData.LastName == null || coachData.Biography == null
                       || coachData.Skills == null || coachData.Username == null
                       || coachData.Email == null)
            {
                ViewBag.ErrorMsg = "Error! There can not be empty fields";
                return View(coachData);
            }

                if (ModelState.IsValid)
            {
                var coach = db.Coaches.Find(coachData.Id);

                if(coach != null) { 
                if (coach.FirstName != coachData.FirstName) coach.FirstName = coachData.FirstName;
                if (coach.LastName != coachData.LastName) coach.LastName = coachData.LastName;
                if (coach.Biography != coachData.Biography) coach.Biography = coachData.Biography;
                if (coach.Skills != coachData.Skills) coach.Skills = coachData.Skills;

                if (coach.Username != coachData.Username) {

                        if (db.Coaches.Where(a => a.Username.ToLower() == coachData.Username.ToLower()).Count() > 0)
                        {
                            ViewBag.DuplicateUserName = "The username you enter is already being used for another coach, try another one";
                            return View(coachData);
                        }
                        coach.Username = coachData.Username;
                    }

                    if (coach.Email != coachData.Email)
                    {

                        if (db.Coaches.Where(a => a.Email.ToLower() == coachData.Email.ToLower()).Count() > 0)
                        {
                            ViewBag.DuplicateEmail = "The email you enter is already being used for another coach, try another one";
                            return View(coachData);
                        }
                        coach.Email = coachData.Email;
                    }


                    try
                {
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    ViewBag.ErrorMsg = "Error! FirstName, LastName, Password, and UserName must have at most 20 characters, \n " +

Code/Website/LifeManagement/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LifeManagement.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult icons()
        {
            return View();
        }
    }
}

Code/Website/LifeManagement/Views/Coaches/CoachEditProfile.cshtml
@model LifeManagement.Models.Coach


<div class="modal-body" id="responseOk">

            <div class="form-horizontal" id="completeForm">
                <h3 style="text-align:center; font-weight:bold">Edit Profile</h3>
                
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

               
                <div class="form-group">
                    <h5 id="EmptyName" class="col-md-offset-2 text-danger"></h5>
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <h5 id="EmptyLastName" class="col-md-offset-2 text-danger"></h5>
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <h5 id="EmptyBiography" class="col-md-offset-2 text-danger"></h5>
                    @Html.LabelFor(model => model.Biography, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Biography,  new { @class = "form-control", rows = "4" } )
                        @Html.ValidationMessageFor(model => model.Biography, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <h5 id="EmptySkills" class="col-md-offset-2 text-danger"></h5>
                    @Html.LabelFor(model => model.Skills, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Skills, new { @class = "form-control", rows = "4" })
                        @Html.ValidationMessageFor(model => model.Skills, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <h5 id="noFile" class="col-md-offset-4 text-danger"></h5>
                    <div class="control-label col-md-4">
                        <label style="text-align:left">Upload a profile picture:</label>
                    </div>
                    <div class="col-md-8">
                        <input type="file" name="file" id="file" style="width: 100%;" />
                    </div>
                </div>

           <br />
                <div class="form-group">
                    <div class="col-md-offset-4">
                        <div class="col-md-4">
                            <button onclick="validate()" class="btn btn-success form-control">Save</button>

                        </div>
                        <div class="col-md-4">
                            <button class="btn btn-primary form-control" data-dismiss="modal">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
    </div>
   

<script src="~/Scripts/lmpopup.js"></script>


<script>
    function validate() {

        if ($("#FirstName").val() == "") {
            $("#EmptyName").html("Your first Name can't be empty");
            return;
        }
        if ($("#LastName").val() == "") {
            $("#EmptyLastName").html("Your Last Name can't be empty");
            return;
        }
        if ($("#Biography").val() == "") {
            $("#EmptyBiography").html("Your biography can't be empty");
            return;
        }
        if ($("#Skills").val() == "") {
            $("#EmptySkills").html("Your skills can't be empty");
            return;
        }

        if ($("#file").val() != "") {
            if (($("#file")[0].files[0].size) >= 2097152)       //2MB
            {
                $("#noFile").html("Image too big, please upload a pic of 2MB or less");
                return;
            }
        }

        var formdata = new FormData();

        var fileInput = $('#file');
        $.each($(fileInput).get(0).files, function (index, value) {
            formdata.append(value.name, value);
        });

        var FirstName = $("#FirstName").val();
        var LastName = $("#LastName").val();
        var Biography = $("#Biography").val();
        var Skills = $("#Skills").val();


        formdata.append("FirstName", FirstName);
        formdata.append("LastName", LastName);
        formdata.append("Biography", Biography);
        formdata.append("Skills", Skills);


        $.ajax({
            url: '@Url.Action("CoachEditProfile", "Coaches")',
            type: 'POST',
            data: formdata,
            contentType: false,
            cache: false,
            processData: false,
            success: function (res) {
                $("#responseOk").html("<h2> Your profile was updated successfully </h2> <button class=\"btn btn-success\" onclick=\" window.location = '@Url.Action("DashBoard", "Coaches", null, Request.Url.Scheme)';\">Done</button>");
                $("#completeForm").html('');
            },
            error: function (msg) {
                $("#responseOk").html("<h2> Some unexpected error happened </h2> <button class=\"btn btn-danger\" data-dismiss=\"modal\">Close</button>");
                $("#completeForm").html('');
            }
        });
    }
</script>

Code/Website/LifeManagement/Views/Coaches/CoachReviews.cshtml
@model LifeManagement.Models.Coach
    @{
        LifeManagement.Models.Common common = new LifeManagement.Models.Common();
    }
<link href="~/Content/Reviews.css" rel="stylesheet" />
<script src="~/Scripts/reviews.js"></script>
<div id="details-section" class="review-div col-md-12">
    @{Html.RenderAction("CoachDetailsPage", new { id = Model.Id });}
</div>
<div class="text-center" style="background: white; padding: 10px; margin-bottom: 20px; display: @(@common.IsAuthenticated?"block":"none")">
    <a class="lmmodal btn btn-sm btn-info" modal-width="600px" url="@Url.Action("WriteReview","Coaches",new {id=Model.Id})">Write Review</a>

</div>
<div id="reviews-section" class="">
    @{Html.RenderAction("ReviewsList", new { id = Model.Id });}
</div>
<script>
    $(document).ready(function() {
        setpopups();
    })
</script>

Code/Website/LifeManagement/Views/Coaches/CoachesList.cshtml
@model List<LifeManagement.Models.Coach>
@{
    var common = new LifeManagement.Models.Common();
}
<link href="~/Content/coaches.css" rel="stylesheet" />


        <table class="table">
            @{
                foreach (var m in Model)
                {
                    <tr>
                        <td>
                            
                                <table class="table coach-table">
                                    <tr class="no-border">
                                        <td class="coachimgtd no-border" rowspan="5"><img class="coachimg" src="@common.SignatureImageStr64(m.Avatar, m.AvatarMime)" /></td>
                                        <td class="no-border">
                                            @(@m.FirstName + " " + m.LastName)

                                        </td>
                                    </tr>
                                    <tr class="no-border">
                                        <td class="no-border">
                                            @{
                                                for (int i = 0; i < m.ReviewScore; i++)
                                                {
                                                    <div class="stardiv">
                                                    </div>
                                                }
                                            }

                                        </td>
                                    </tr>
                                    <tr class="no-border">
                                        <td class="no-border">@m.Skills</td>
                                    </tr>
                                    <tr class="no-border">
                                        <td class="no-border">@m.Email</td>
                                    </tr>
                                    <tr class="no-border">
                                        <td class="no-border">
                                            <a class="lmmodal" modal-width="700px" href="#" url="/Coaches/CoachDetailsPage/@m.Id">Details</a> |
                                            <a href="@Url.Action("SeeReviews","Coaches",new {id=m.Id})">Reviews</a>
                                         </td>

                                    </tr>

                                    <tr class="no-border"><td class="no-border" colspan="2"><hr /></td></tr>
                                </table>
                            
                        </td>
                    </tr>
                                                }
            }

        </table>




<link href="~/Content/coaches.css" rel="stylesheet" />


<script>
    $(document).ready(function () {
        setpopups();
    })
</script>

Code/Website/LifeManagement/Views/Coaches/Delete.cshtml
@model LifeManagement.Models.Coach

@{
    ViewBag.Title = "Delete";
}

@{
    var common = new LifeManagement.Models.Common();
}

@{
    Layout = "../Shared/AdminDashBoardLayout.cshtml";
}

<div class="clearfix coach-tabs" >

    <div class=" text-center">

        <h2>Delete</h2>

        <h3>Are you sure you want to delete this Coach?</h3>
        <div>
            <h5 style="color:red">Please note that all information related to this coach will be deleted as well, and changes are not reversible.</h5>
            <br />
            <hr />
            <div style="word-break: break-all; word-wrap: break-word;">
                <br />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Avatar)
                    </dt>
                    <dd>
                        <div class="coach-avatar-container">
                            <img class=" coach-avatar-img " src="@common.SignatureImageStr64(Model.Avatar, Model.AvatarMime)">
                        </div>
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.FirstName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.FirstName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.LastName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.LastName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.ReviewScore)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ReviewScore)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Biography)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Biography)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Skills)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Skills)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Username)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Username)
                    </dd>
                </dl>
</div>
            </div>
        <hr />
        <br />
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" /> &nbsp;
                    @Html.ActionLink("Cancel", "Index", "Coaches", null, new { @class = "btn btn-success" })
                </div>
            }
        </div>

        <br />   
</div>

Code/Website/LifeManagement/Views/Coaches/ResetPass.cshtml
<div  style="width: 530px ; ">
    <h2 class="text-center"> Recovery instructions were sent succefully to your email</h2>

    <br />
    <br />
    <div class="form-group">
        <div class="col-md-offset-8 col-md-4">
            <button class="btn btn-success form-control" data-dismiss="modal">
                Done
            </button>
        </div>
    </div>

</div>

Code/Website/LifeManagement/Views/Coaches/ReviewsList.cshtml
@model List<LifeManagement.Models.CoachReview>

<div class="clearfix">
    @foreach (var m in Model)
    {
        <div class="review-div col-md-12">
            <div class="stars-div">
                @{
                    for (int i = 0; i < m.Score; i++)
                    {
                        <div class="stardiv">
                        </div>
                    }}
            </div>
            <div class="author-div col-md-12">
                Author: @m.User.FirstName <br />
                Date Posted: @m.DateApproved.Value.ToShortDateString()
            </div>
            <div class="review-text col-md-12">
                @m.Review
            </div>
        </div>
                    }
</div>

Code/Website/LifeManagement/Views/Coaches/ShareProgress.cshtml
<h2> Select a coach to share your progress</h2>
@{Html.RenderAction("CoachesList");}

Code/Website/LifeManagement/Views/Coaches/WriteReview.cshtml
@model int
    <div class="clearfix">
        <div class="form-horizontal">
            <div class="col-md-12 text-warning" id="errors"></div>
            <div class="form-group">
                <label class="score-question control-label col-md-8"> How many stars would you give this coach?</label>
                <div class="score-div col-md-4">
                    <ul class="list-inline stars-list">
                        <li class="score-li stardiv" score="1"></li>
                        <li class="score-li stardiv" score="2"></li>
                        <li class="score-li stardiv" score="3"></li>
                        <li class="score-li stardiv" score="4"></li>
                        <li class="score-li stardiv" score="5"></li>
                    </ul>
                </div>

            </div>
            <div class="form-group">
                <div class="col-md-12">
                    <textarea class="form-control " id="review" rows="4" placeholder="write your review"></textarea>

                </div>
               
            </div>
            <div class="form-group">
                <div class="col-md-12 text-center">
                    <button onclick="saveReview()" class="btn btn-sm btn-info">Send for approval</button>
                </div>
            </div>
        </div>
    </div>

<script>
    var coachscore = 5;
    $(document).ready(function() {

        setStars();
    })


    function setStars() {
        $('.score-li').click(function() {
            var score = $(this).attr("score");
            coachscore = score;

            $('.score-li').each(function() {
                var thisscore = $(this).attr("score");
                if (thisscore <= score) {
                    $(this).addClass("stardiv");
                    $(this).removeClass("stardiv-clear");
                } else {
                    $(this).addClass("stardiv-clear");
                    $(this).removeClass("stardiv");
                }
            });
        })
    }

    function saveReview() {
        var data = {
            review: $("#review").val(),
            coachid: @Model,
            score: coachscore
        }
        $.ajax({
            url:'@Url.Action("SaveReview","Coaches")',
            data:data,
            type:'POST',
            success:function(res) {
                $("#basicModal").modal('hide');
            },
            error:function(msg) {
                
                $("#errors").html("Error: need to write a review");

            }
        })
    }


</script>