Code/Website/LifeManagement/Controllers/CoachReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LifeManagement.Models;
using System.Data.Entity;

namespace LifeManagement.Controllers
{
    public class CoachReviewsController : Controller
    {
        private SeniorDBEntities db = new SeniorDBEntities();
        // GET: CoachReviews
        public PartialViewResult Revise()
        {
            return PartialView();
        }
        [Authorize(Roles="Admin")]
        public PartialViewResult PendingList()
        {
            var pending = db.CoachReviews.Where(a => a.ApprovedBy == null);
            if (pending.Any())
                return PartialView("PendingList",pending.ToList());

            ViewBag.ErrorMsg = "No pending reviews";
            return PartialView("ErrorPartial");

        }

        public PartialViewResult Details(int id)
        {
            var review = db.CoachReviews.Find(id);
            if (review == null)
            {
                ViewBag.ErrorMsg = "Invalid review";
                return PartialView("ErrorPartial");
            }
            return PartialView(review);
        }

        public PartialViewResult CompleteReview(int id, bool isApproved)
        {
            var admin = db.Users.Where(a => a.username.ToLower() == User.Identity.Name.ToLower() && a.Role.Name=="Admin").FirstOrDefault();
            if (admin == null)
            {
                ViewBag.ErrorMsg = "Cannot approve or reject. Not an admin";
                return PartialView("ErrorPartial");
            }
            var review = db.CoachReviews.Find(id);
            if (review == null)
            {
                ViewBag.ErrorMsg = "Invalid review";
                return PartialView("ErrorPartial");
            }
            db.Entry(review).State = EntityState.Modified;

            review.Approved = isApproved;
            review.DateApproved=DateTime.Now;
            review.ApprovedBy = admin.Id;
            db.SaveChanges();

            recalculateScore(review.CoachId);
            
            return PendingList();


        }

        private void recalculateScore(int coachid)
        {
            var coach = db.Coaches.Find(coachid);
            if (coach != null)
            {
                var reviews = coach.CoachReviews.Where(a => a.Approved == true);
                coach.ReviewScore = (int) (reviews.Sum(a => a.Score) / reviews.Count());
                db.SaveChanges();
            }
        }
    }
}

Code/Website/LifeManagement/Views/CoachReviews/Details.cshtml
@model LifeManagement.Models.CoachReview
@{
    LifeManagement.Models.Common common = new LifeManagement.Models.Common();
}
<link href="~/Content/Reviews.css" rel="stylesheet" />

<div class="review-div clearfix">
    <div id="approveerrors" class="text-danger"></div>
    <div class="col-md-12 text-center">
        <img class="user-image" src="@common.SignatureImageStr64(Model.Coach.Avatar, Model.Coach.AvatarMime)"/>

    </div>

    <div class="stars-div col-md-12">
        @{
            for (int i = 0; i < Model.Score; i++)
            {
                <div class="stardiv">
                </div>
            }}
    </div>
    <div class="author-div col-md-12">
        Author: @Model.User.FirstName <br/>

    </div>
    <div class="review-text col-md-12">
        @Model.Review
    </div>
    <div class="col-md-12 text-center">
        <button class="btn btn-sm btn-success" onclick="revise(true)">Approve</button>
        <button class="btn btn-sm btn-danger" onclick="revise(false)">Reject</button>
    </div>
</div>


               
<script>
    function revise(isApproved) {
        var data= {
            id:@Model.Id,
            isApproved:isApproved
        }
        $.ajax({
            url: '@Url.Action("CompleteReview","CoachReviews")',
            type: 'POST',
            data: data,
            success: function(msg) {
                $("#pending-list").html(msg);
                $("#basicModal").modal('hide');
            },
            error: function(res) {
                $("#approveerrors").html("Could not complete review")
            }
        });
    }
</script>
<style>
    .review-div {
        max-height: 1000px !important;
    }
</style>

Code/Website/LifeManagement/Views/CoachReviews/PendingList.cshtml
@model List<LifeManagement.Models.CoachReview>
    @{
        LifeManagement.Models.Common common = new LifeManagement.Models.Common();
    }
<link href="~/Content/coaches.css" rel="stylesheet" />
<link href="~/Content/Reviews.css" rel="stylesheet" />
@foreach (var m in Model)
{
    <div class="review-div lmmodal" modal-width="600px" url="@Url.Action("Details","CoachReviews",new {id=m.Id})">
        <div  style="float:left ">
            <img class="user-image" src="@common.SignatureImageStr64(m.User.Avatar,m.User.AvatarMime)"/>

            @(@"User: " + m.User.FirstName + " " + m.User.LastName + " reviewed Coach: " + m.Coach.FirstName + " " + m.Coach.LastName + " with score: ")
        </div>
        <div>
            @for (int i = 0; i < m.Score; i++)
            {
                <div class="stardiv"></div>
            }
        </div>
    </div>
}
<script>
    $(document).ready(function() {
        setpopups();
    })
</script>

Code/Website/LifeManagement/Views/CoachReviews/Revise.cshtml
<h4>Reviews Pending Approval </h4>
<div id="pending-list">
    @{Html.RenderAction("PendingList");}
</div>